
export const actionTypes = {
    SET_ADDRESS_DATA: "SET_ADDRESS_DATA",
    SET_UTILITY_DATA: "SET_UTILITY_DATA",
    SET_PLAN_DATA: "SET_PLAN_DATA",
    SET_PLAN_REQUEST: "SET_PLAN_REQUEST",

    ADD_FIELD_DATA: "ADD_FIELD_DATA",
    SET_FIELD_INPUT: "SET_FIELD_INPUT",
    SET_FIELD_IS_DISABLED: "SET_FIELD_IS_DISABLED",
    SET_FIELD_TRANSIENT_IS_DISABLED: "SET_FIELD_TRANSIENT_IS_DISABLED",
    SET_FIELD_IS_VALIDATED: "SET_FIELD_IS_VALIDATED",
    SET_FIELD_IS_VALIDATED_CLASS: "SET_FIELD_IS_VALIDATED_CLASS",
    SET_FIELD_IS_TOGGLED: "SET_FIELD_IS_TOGGLED",
    SET_FIELD_TOGGLE_IS_DISABLED: "SET_FIELD_TOGGLE_IS_DISABLED",

    ADD_FORM_DATA: "ADD_FORM_DATA",
    SET_FORM_IS_DISABLED: "SET_FORM_IS_DISABLED",
    SET_FORM_IS_VALIDATED: "SET_FORM_IS_VALIDATED",
    SET_FORM_IS_SUBMITTED: "SET_FORM_IS_SUBMITTED",
    SET_FORM_IS_LOADING: "SET_FORM_IS_LOADING",
    SET_FORM_FEEDBACK: "SET_FORM_FEEDBACK",
    SET_FORM_UPDATE_IS_REQUIRED: "SET_FORM_UPDATE_IS_REQUIRED"
  };




  